### ISSUE TITLE
getResultInfo 获取响应结果并处理对应状态

### ISSUE THREAD

**Issue by huangkemingyyds** [Hansen-hjs/vue-admin#3]
好哥哥，使用中发现响应结果嵌套了哦。
![image](https://github.com/Travis-hjs/vue-admin/assets/66153067/12efec1f-4a2e-446b-ad4c-10fd8dfe349f)

**Comment by Travis-hjs** [comment]
自定义的数据结构根据后端的返回数据结构自行定义，我这边不需要data.data，这里的操作是要开发者自己去修改的，因为不是所有服务端数据结构都一样，PageInfo的字段同理
