### ISSUE TITLE
【功能建议】希望能设置一个the-layout-tags的默认逻辑

### ISSUE THREAD

**Issue by cvpv** [Hansen-hjs/vue-admin#5]
虽然联动逻辑可能是需要开发者自己定义，但是我个人觉得，还是应该做一个基础的逻辑供新手参考

```javascript
// src\layout\components\HeaderBar.vue
function onRemove(index: number) {
  layoutInfo.historyViews.splice(index, 1);
}
```
上面代码

个人建议可以增加

1、首页router不允许删除
2、删除tag后，同时在vue-router中出栈对应的页面，

**Comment by Travis-hjs** [comment]
这种功能不是必要的，所以不打算加，而且根据每个项目的需求都不同，没有办法做到统一；像一些业务代码的场景中，带有`/page/:id`这种的场景，用上面的逻辑就需要做特殊处理
